apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-pod
      app:  voting-app
  template:
    metadata:
      name: postgress-pod
      labels:
        name: postgress-pod
        app:  voting-app
    spec:
      containers:
      - name: postgress
        image:  postgress:9.4
        ports:
        - containerPort: 5432